// FFI bindings for mtmd (multimodal/vision support via llama.cpp).
// Generated by build.rs; used by the LlamaCppModel vision path.
#![allow(nonstandard_style, dead_code, unused_imports, clippy::all)]

include!(concat!(env!("OUT_DIR"), "/mtmd_bindings.rs"));
