// Output filtering: thinking-block suppression, control-token holdback,
// and user-supplied stop-sequence detection.
//
// Extracted from engine/mod.rs so the logic can be tested without the full
// inference engine. `InferenceEngine` uses `PerRequestState` and the
// free functions directly through `use super::output_filter::*`.

/// Special token patterns that mark end-of-turn or other control sequences.
/// These are detected in `check_stop_sequences` using a rolling buffer so that
/// patterns spanning multiple tokens (e.g. `<`, `|`, `im_end`, `|`, `>`) are
/// also caught.  Never emitted to the user.
pub(super) const CONTROL_TOKEN_PATTERNS: &[&str] = &[
    "<|im_end|>",
    "<|im_start|>",
    "<|endoftext|>",
    "<|endofthought|>",
];

// ---------------------------------------------------------------------------
// Per-request output state
// ---------------------------------------------------------------------------

/// Per-request mutable state for output processing.
#[derive(Default)]
pub(crate) struct PerRequestState {
    /// True while we are inside a `<think>…</think>` block.
    pub(super) in_thinking: bool,
    /// When true the `<think>…</think>` block is forwarded to the caller instead
    /// of being silently discarded.  Set from `SamplingParams::show_thinking`.
    pub(super) show_thinking: bool,
    /// Text that has passed the thinking filter but is being held back until
    /// we know it is not the start of a control-token pattern (e.g. `<|im_end|>`
    /// arriving across several BPE tokens: `<`, `|`, `im_end`, `|`, `>`).
    pub(super) pending_output: String,
    /// Rolling suffix of recently emitted text (length ≤ 2 × max_stop_len).
    /// Used to detect *user-supplied* stop strings that span multiple tokens.
    pub(super) text_buffer: String,
    /// Model-native stop token strings (EOS/EOT text forms) treated exactly like
    /// `CONTROL_TOKEN_PATTERNS`: held back in `pending_output` until the full
    /// pattern is assembled, then suppressed and generation stops.
    pub(super) model_control_patterns: Vec<String>,
    /// Accumulator for raw token bytes that may form an incomplete UTF-8 sequence
    /// (e.g. the first two bytes of a 4-byte emoji split across BPE tokens).
    /// Bytes are drained into valid UTF-8 strings before entering the filter
    /// pipeline, preventing `String::from_utf8_lossy` replacement artifacts (??).
    pub(super) utf8_buf: Vec<u8>,
    /// Number of `<think>…` characters accumulated in the current thinking block.
    /// Reset each time a new `<think>` tag is entered.
    pub(super) thinking_chars: usize,
    /// Maximum characters allowed inside a `<think>…` block before it is
    /// force-closed.  0 = no limit.  Set from `SamplingParams::max_thinking_chars`.
    pub(super) max_thinking_chars: usize,
    /// When true, prepend `<think>\n` to the very first emitted token.
    /// Set when `initial_in_thinking=true` so that clients see a well-formed
    /// `<think>…</think>` block even though the opening tag was injected into
    /// the prompt rather than generated by the model.
    pub(super) emit_think_open_tag: bool,
}

// ---------------------------------------------------------------------------
// Pure helpers (no self, no lock)
// ---------------------------------------------------------------------------

/// Apply output filtering rules.
///
/// Returns `(text_to_pass_downstream, control_stop)`.
/// * `text_to_pass_downstream` — safe visible text (empty while thinking or holding back
///   a partial control-token prefix).
/// * `control_stop` — `true` when a complete control-token pattern (`<|im_end|>` etc.)
///   was detected, meaning generation should stop.
///
/// **Why two stages?**
/// Models like Qwen3.5 often generate `<|im_end|>` as 5–6 separate BPE tokens
/// (`<`, `|`, `im`, `_end`, `|`, `>`).  A single-token `contains("<|")` check
/// misses this.  We therefore buffer the output in `state.pending_output` and
/// only flush text that cannot be the start of a control pattern.
pub(crate) fn apply_output_filter(state: &mut PerRequestState, raw: &str) -> (String, bool) {
    if raw.is_empty() {
        return (String::new(), false);
    }

    // When the prompt already ends with `<think>\n` (initial_in_thinking=true),
    // the model never generates the opening tag. Emit it once on the first token
    // so that the output stream is well-formed `<think>…</think>` for clients.
    if state.emit_think_open_tag {
        state.emit_think_open_tag = false;
        if state.show_thinking {
            let (rest, stop) = apply_output_filter(state, raw);
            return (format!("<think>\n{rest}"), stop);
        }
    }

    // Build combined pattern list: static patterns + model-native stop token strings.
    // SAFETY: the Vec<&str> borrows from `state.model_control_patterns` which lives for
    // the duration of this call.  We reborrow `state` fields individually below to
    // avoid a borrow-checker conflict with `state.pending_output`.
    let patterns = all_control_patterns(&state.model_control_patterns);

    // 1. Enter <think> block (usually a single special token like 248068 for Qwen3.5).
    if raw.contains("<think>") {
        state.in_thinking = true;
        state.thinking_chars = 0; // reset budget counter for each new block
        if state.show_thinking {
            // Emit the <think> tag so the user can see when reasoning starts.
            return (raw.to_string(), false);
        }
        return (String::new(), false);
    }

    // 2. Exit <think> block; text *after* the closing tag goes to the pending buffer.
    if raw.contains("</think>") {
        state.in_thinking = false;
        if state.show_thinking {
            // Emit the closing tag, then flush whatever was pending.
            let after_tag = raw
                .find("</think>")
                .map(|i| i + "</think>".len())
                .unwrap_or(raw.len());
            let mut out = raw[..after_tag].to_string();
            // Any text after </think> in the same token also needs to be flushed.
            if after_tag < raw.len() {
                state.pending_output.push_str(&raw[after_tag..]);
                let (rest, stop) = flush_pending_output(&mut state.pending_output, &patterns);
                out.push_str(&rest);
                if stop {
                    return (out, true);
                }
            }
            return (out, false);
        }
        // Normal mode: discard the tag, keep text after it.
        if let Some(idx) = raw.find("</think>") {
            let after = idx + "</think>".len();
            if after < raw.len() {
                state.pending_output.push_str(&raw[after..]);
            }
        }
        return flush_pending_output(&mut state.pending_output, &patterns);
    }

    // 3. Inside a thinking block.
    if state.in_thinking {
        // Budget enforcement: force-close the block when the character limit is reached.
        // This prevents infinite thinking loops where the model never generates `</think>`.
        if state.max_thinking_chars > 0 {
            state.thinking_chars += raw.chars().count();
            if state.thinking_chars >= state.max_thinking_chars {
                state.in_thinking = false;
                // Emit a synthetic closing tag so show_thinking output is well-formed,
                // then let subsequent tokens flow through as normal response content.
                if state.show_thinking {
                    return ("</think>\n".to_string(), false);
                }
                return (String::new(), false);
            }
        }
        if state.show_thinking {
            // Emit thinking tokens directly (no holdback needed — control patterns
            // like <|im_end|> should not appear inside a thinking block).
            return (raw.to_string(), false);
        }
        return (String::new(), false);
    }

    // 4. Normal text: push through the pending buffer; hold back any partial
    //    control-token prefix (e.g. `<` that could be the start of `<|im_end|>`).
    state.pending_output.push_str(raw);
    flush_pending_output(&mut state.pending_output, &patterns)
}

/// Flush as much of `pending` as is safe.
///
/// 1. If `pending` contains a complete control-token pattern, emit everything
///    *before* the pattern and signal stop (the pattern itself is discarded).
/// 2. Otherwise, hold back the longest suffix that is a strict prefix of any
///    control pattern (could be the start of `<|im_end|>` etc.).
///
/// `patterns` is the combined list of static `CONTROL_TOKEN_PATTERNS` plus any
/// model-native stop token strings for the current request.
pub(super) fn flush_pending_output(pending: &mut String, patterns: &[&str]) -> (String, bool) {
    // Check for complete control-token patterns.
    for &pat in patterns {
        if let Some(idx) = pending.find(pat) {
            let emit = pending[..idx].to_string();
            pending.clear();
            return (emit, true); // stop generation
        }
    }

    // Find the earliest `<` that could be the start of a control pattern.
    let holdback_start = find_holdback_start(pending, patterns);
    let emit = pending[..holdback_start].to_string();
    *pending = pending[holdback_start..].to_string();
    (emit, false)
}

/// Returns the byte offset of the first `<` in `text` from which a control-token
/// pattern *could* still begin (i.e. some pattern starts with the suffix
/// `text[offset..]`).  Returns `text.len()` when nothing needs to be held back.
fn find_holdback_start(text: &str, patterns: &[&str]) -> usize {
    for (i, c) in text.char_indices() {
        if c != '<' {
            continue;
        }
        let suffix = &text[i..];
        if patterns.iter().any(|p| p.starts_with(suffix)) {
            return i;
        }
    }
    text.len()
}

/// Build the combined pattern list for a request: static CONTROL_TOKEN_PATTERNS
/// plus any model-native stop token strings stored in state.
pub(super) fn all_control_patterns(model_pats: &[String]) -> Vec<&str> {
    let mut v: Vec<&str> = CONTROL_TOKEN_PATTERNS.to_vec();
    for p in model_pats {
        if !v.contains(&p.as_str()) {
            v.push(p.as_str());
        }
    }
    v
}

/// Check whether the rolling text buffer (extended with `new_text`) ends with
/// any of the user-supplied stop strings.
///
/// Returns `(text_to_emit, was_stopped)`. When stopped, `text_to_emit` is
/// the prefix of `new_text` that appears *before* the stop string; the stop
/// string itself is NOT emitted (OpenAI spec behaviour).
///
/// Note: built-in control-token patterns (`<|im_end|>` etc.) are already handled
/// upstream in `apply_output_filter` / `flush_pending_output`.  This function
/// only deals with user-supplied stop strings.
pub(crate) fn check_stop_sequences(
    state: &mut PerRequestState,
    new_text: String,
    stop: &Option<Vec<String>>,
) -> (String, bool) {
    let stops = match stop.as_deref() {
        Some(s) if !s.is_empty() => s,
        _ => {
            // No stop strings — just maintain the buffer for future calls.
            state.text_buffer.push_str(&new_text);
            trim_text_buffer(&mut state.text_buffer, 0);
            return (new_text, false);
        }
    };

    let max_stop_len: usize = stops.iter().map(|s| s.len()).max().unwrap_or(0);

    // Extend the buffer with the new token text.
    state.text_buffer.push_str(&new_text);

    // Check every stop string.
    for stop_str in stops {
        if stop_str.is_empty() {
            continue;
        }
        if state.text_buffer.ends_with(stop_str.as_str()) {
            // Find how much of `new_text` to emit (the part before the stop string).
            let buf_len = state.text_buffer.len();
            let stop_start_in_buf = buf_len - stop_str.len();
            // `new_text` starts at `buf_len - new_text.len()` within the buffer.
            let text_start_in_buf = buf_len.saturating_sub(new_text.len());

            let emit = if stop_start_in_buf >= text_start_in_buf {
                let offset = stop_start_in_buf - text_start_in_buf;
                new_text[..offset].to_string()
            } else {
                // Stop string began in a previously-emitted token — emit nothing.
                String::new()
            };

            state.text_buffer.clear();
            return (emit, true);
        }
    }

    // No match — trim the buffer to avoid unbounded growth.
    trim_text_buffer(&mut state.text_buffer, max_stop_len);
    (new_text, false)
}

/// Drain as many complete UTF-8 codepoints as possible from the front of `buf`.
///
/// Returns the valid UTF-8 prefix as a `String` and leaves any trailing
/// incomplete byte sequence in `buf` to be completed by the next token.
/// At EOS, callers should call this with an empty append (no-op) and then
/// discard any residual bytes (which represent a malformed sequence).
pub(crate) fn drain_valid_utf8(buf: &mut Vec<u8>) -> String {
    if buf.is_empty() {
        return String::new();
    }
    match std::str::from_utf8(buf) {
        Ok(s) => {
            let result = s.to_string();
            buf.clear();
            result
        }
        Err(e) => {
            let valid_up_to = e.valid_up_to();
            // SAFETY: valid_up_to is guaranteed by from_utf8 to be a char boundary.
            let valid = unsafe { std::str::from_utf8_unchecked(&buf[..valid_up_to]) }.to_string();
            *buf = buf[valid_up_to..].to_vec();
            valid
        }
    }
}

/// Keep only the trailing `max_stop_len` characters of the buffer (aligned to a char boundary).
pub(super) fn trim_text_buffer(buf: &mut String, max_stop_len: usize) {
    let keep = (max_stop_len * 2).max(128);
    if buf.len() > keep {
        let trim_byte = buf.len() - keep;
        // Walk forward to the next valid char boundary.
        let trim_at = buf
            .char_indices()
            .map(|(i, _)| i)
            .find(|&i| i >= trim_byte)
            .unwrap_or(trim_byte);
        *buf = buf[trim_at..].to_string();
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn stops(v: &[&str]) -> Option<Vec<String>> {
        Some(v.iter().map(|s| s.to_string()).collect())
    }

    // Helper: unwrap the text from apply_output_filter (ignores the control_stop bool)
    fn aof(state: &mut PerRequestState, raw: &str) -> String {
        apply_output_filter(state, raw).0
    }

    // --- apply_output_filter ---

    #[test]
    fn test_filter_think_block() {
        let mut s = PerRequestState::default();
        assert_eq!(aof(&mut s, "<think>"), "");
        assert!(s.in_thinking);
        assert_eq!(aof(&mut s, "internal thought"), "");
        assert_eq!(aof(&mut s, "</think> hello"), " hello");
        assert!(!s.in_thinking);
        assert_eq!(aof(&mut s, " world"), " world");
    }

    #[test]
    fn test_filter_passthrough() {
        let mut s = PerRequestState::default();
        assert_eq!(aof(&mut s, "hello"), "hello");
        assert_eq!(aof(&mut s, " world"), " world");
    }

    #[test]
    fn test_filter_control_single_token_stopped() {
        // Single-token <|im_end|> (e.g. EOS token decoded to its text form) must stop.
        let mut s = PerRequestState::default();
        let (text, stop) = apply_output_filter(&mut s, "<|im_end|>");
        assert_eq!(text, "");
        assert!(stop, "<|im_end|> single token must trigger control stop");
    }

    #[test]
    fn test_filter_control_multi_token_im_end() {
        // Qwen3.5 emits <|im_end|> as 5 separate BPE tokens.
        let mut s = PerRequestState::default();
        for tok in &["<", "|", "im", "_end", "|"] {
            let (text, stop) = apply_output_filter(&mut s, tok);
            assert_eq!(text, "", "partial token '{tok}' must be held back");
            assert!(!stop, "no stop on partial token '{tok}'");
        }
        let (text, stop) = apply_output_filter(&mut s, ">");
        assert_eq!(text, "", "closing '>' must not leak");
        assert!(stop, "closing '>' completes <|im_end|> → must stop");
    }

    #[test]
    fn test_filter_holdback_released_on_non_pattern() {
        // A lone `<` is held back until the next token confirms it is not a control pattern.
        let mut s = PerRequestState::default();
        let (t1, _) = apply_output_filter(&mut s, "<");
        assert_eq!(t1, "", "< must be held back");
        // `x` cannot extend any control pattern starting with `<` → release both.
        let (t2, stop) = apply_output_filter(&mut s, "x");
        assert_eq!(t2, "<x", "< and x must be released together");
        assert!(!stop);
    }

    #[test]
    fn test_filter_text_before_control_token_emitted() {
        // Normal text followed by <|im_end|>: text emitted, pattern stops generation.
        let mut s = PerRequestState::default();
        assert_eq!(aof(&mut s, "Hello!"), "Hello!");
        let (text, stop) = apply_output_filter(&mut s, "<|im_end|>");
        assert_eq!(text, "");
        assert!(stop);
    }

    // --- check_stop_sequences ---

    #[test]
    fn test_stop_no_stops_configured() {
        let mut s = PerRequestState::default();
        let (text, hit) = check_stop_sequences(&mut s, "hello world".to_string(), &None);
        assert_eq!(text, "hello world");
        assert!(!hit);
    }

    #[test]
    fn test_stop_exact_single_token() {
        let mut s = PerRequestState::default();
        let (text, hit) = check_stop_sequences(&mut s, "User:".to_string(), &stops(&["User:"]));
        assert_eq!(text, "", "stop string itself must not be emitted");
        assert!(hit);
    }

    #[test]
    fn test_stop_partial_current_token_emitted() {
        let mut s = PerRequestState::default();
        let (text, hit) =
            check_stop_sequences(&mut s, "Hello\nUser:".to_string(), &stops(&["\nUser:"]));
        assert_eq!(text, "Hello");
        assert!(hit);
    }

    #[test]
    fn test_stop_multi_token_span() {
        let mut s = PerRequestState::default();
        let (t1, h1) = check_stop_sequences(&mut s, "Hello\n".to_string(), &stops(&["\nUser:"]));
        assert_eq!(t1, "Hello\n");
        assert!(!h1);
        let (t2, h2) = check_stop_sequences(&mut s, "User:".to_string(), &stops(&["\nUser:"]));
        assert_eq!(t2, "");
        assert!(h2);
    }

    #[test]
    fn test_stop_multiple_candidates_first_wins() {
        let mut s = PerRequestState::default();
        let (text, hit) =
            check_stop_sequences(&mut s, "STOP".to_string(), &stops(&["STOP", "OTHER"]));
        assert_eq!(text, "");
        assert!(hit);
    }

    #[test]
    fn test_stop_no_match_passes_through() {
        let mut s = PerRequestState::default();
        let (t1, h1) = check_stop_sequences(&mut s, "hello ".to_string(), &stops(&["User:"]));
        assert_eq!(t1, "hello ");
        assert!(!h1);
        let (t2, h2) = check_stop_sequences(&mut s, "world".to_string(), &stops(&["User:"]));
        assert_eq!(t2, "world");
        assert!(!h2);
    }

    // --- thinking budget enforcement ---

    fn state_with_budget(max_thinking_chars: usize) -> PerRequestState {
        PerRequestState {
            max_thinking_chars,
            ..Default::default()
        }
    }

    #[test]
    fn test_budget_not_exceeded_passes_through_normally() {
        let mut s = state_with_budget(100);
        // Enter thinking block.
        assert_eq!(aof(&mut s, "<think>"), "");
        assert!(s.in_thinking);
        // Short thought — well under budget.
        assert_eq!(aof(&mut s, "short"), "");
        assert!(s.in_thinking, "should still be thinking");
        // Normal close.
        assert_eq!(aof(&mut s, "</think> answer"), " answer");
        assert!(!s.in_thinking);
    }

    #[test]
    fn test_budget_force_closes_thinking_block() {
        // Budget of 5 chars: the 6-char token "123456" should trigger force-close.
        let mut s = state_with_budget(5);
        assert_eq!(aof(&mut s, "<think>"), "");
        assert!(s.in_thinking);
        // 6 chars — exceeds budget of 5.
        assert_eq!(aof(&mut s, "123456"), "");
        assert!(!s.in_thinking, "budget exceeded → in_thinking must be false");
        // Next tokens flow through as normal response content.
        assert_eq!(aof(&mut s, "hello"), "hello");
    }

    #[test]
    fn test_budget_force_closes_with_show_thinking() {
        let mut s = state_with_budget(5);
        s.show_thinking = true;
        // Enter + enter budget via tag (tag is returned in show_thinking mode).
        let tag_out = aof(&mut s, "<think>");
        assert_eq!(tag_out, "<think>");
        assert!(s.in_thinking);
        // 6 chars — exceeds budget → synthetic </think>\n emitted.
        let out = aof(&mut s, "123456");
        assert_eq!(out, "</think>\n", "synthetic close tag must be emitted");
        assert!(!s.in_thinking);
        // Subsequent tokens are normal output.
        assert_eq!(aof(&mut s, "response"), "response");
    }

    #[test]
    fn test_budget_zero_means_no_limit() {
        let mut s = state_with_budget(0); // 0 = unlimited
        assert_eq!(aof(&mut s, "<think>"), "");
        // Pump in a lot of content — should never force-close.
        for _ in 0..100 {
            assert_eq!(aof(&mut s, "aaaaaaaaaa"), ""); // 10 chars per call, 1000 total
            assert!(s.in_thinking, "no limit → always stays in thinking");
        }
        // Normal close still works.
        assert_eq!(aof(&mut s, "</think> done"), " done");
        assert!(!s.in_thinking);
    }

    #[test]
    fn test_budget_resets_on_new_think_block() {
        let mut s = state_with_budget(10);
        // First block: use 8 chars, then close normally.
        assert_eq!(aof(&mut s, "<think>"), "");
        assert_eq!(aof(&mut s, "12345678"), ""); // 8 chars used
        assert_eq!(aof(&mut s, "</think>"), "");
        assert_eq!(s.thinking_chars, 8);
        // Second block: budget counter must reset on entry.
        assert_eq!(aof(&mut s, "<think>"), "");
        assert_eq!(s.thinking_chars, 0, "budget counter must reset on re-entry");
        assert_eq!(aof(&mut s, "12345678"), ""); // still within budget
        assert!(s.in_thinking);
    }

    // --- trim_text_buffer ---

    #[test]
    fn test_trim_buffer_below_limit_unchanged() {
        let mut buf = "hello".to_string();
        trim_text_buffer(&mut buf, 10); // keep = 20, buf.len() = 5 < 20
        assert_eq!(buf, "hello");
    }

    #[test]
    fn test_trim_buffer_trims_to_trailing_content() {
        let mut buf = "a".repeat(200);
        trim_text_buffer(&mut buf, 10); // keep = 20
        assert!(buf.len() <= 200);
        assert!(buf.len() >= 20);
        // Verify suffix is preserved
        assert!(buf.chars().all(|c| c == 'a'));
    }
}
